### ISSUE TITLE
Pushing module error: "TypeError: Cannot call method 'match' of undefined"

### ISSUE THREAD

**Issue by marcellodesales** [georgy/nexus-npm-repository-plugin#22]
I installed the latest 2.9.1-01 with this plugin and everything worked fine... After defining the hosted, proxied and groups, and I tried to publish a module and it failed with the error below... Even though it is a client issue, is the problem related to the server not returning the correct data?

```
My client is as follows:
$ npm --version
1.3.10
```

Trying to publish with the test .npmrc suggested in the plugin page.

```
mdesales@ubuntu ~/dev/icode/isp-monitoring (master *+) $ npm publish
npm http PUT http://localhost:8081/nexus/content/repositories/npmhosted/isp-monitoring
npm http 401 http://localhost:8081/nexus/content/repositories/npmhosted/isp-monitoring
npm ERR! TypeError: Cannot call method 'match' of undefined
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:119:29)
npm ERR!     at cb (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:158:9)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "publish"
npm ERR! cwd /home/mdesales/dev/icode/isp-monitoring
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_call
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mdesales/dev/icode/isp-monitoring/npm-debug.log
npm ERR! not ok code 0
```

Any help appreciated!

thanks!
Marcello

**Comment by marcellodesales** [comment]
Nexus released the version of this at 2.10... https://issues.sonatype.org/browse/NEXUS-5852
